version: "0.0"

services:
  server-app:
    container_name: server-app
    build:
      context: ./server-app
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    volumes:
      - ./server-app:/usr/src/app
      - $HOME/.cache/pip-docker/:/root/.cache/pip
    env_file:
      - ./env-vars/server-app.txt # you should create this file
    ports:
      - 8000:8000

    # depends_on:
    #   - redis

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  celery-worker:
    container_name: celery-worker
    build:
      context: ./server-app
    command: celery --app=config worker -l INFO -B
    volumes:
      - ./server-app:/usr/src/app
      - $HOME/.cache/pip-docker/:/root/.cache/pip
    env_file:
      - ./env-vars/server-app.txt # you should create this file
