# Generated by Django 5.0.7 on 2024-08-01 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_message_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='kind',
            new_name='log_level',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='log',
            name='id',
        ),
        migrations.AddField(
            model_name='log',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('device_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
