# Generated by Django 5.0.7 on 2024-08-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_kind_log_log_level_rename_content_log_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicatoin',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_type', models.CharField(max_length=50)),
                ('command_message', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.device')),
            ],
        ),
    ]
