# Generated by Django 4.2 on 2024-08-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_applicatoin_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
