# Generated by Django 5.0.7 on 2024-08-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_target_user'),
    ]

    operations = [
    ]
