# Generated by Django 5.0.7 on 2024-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
