# Generated by Django 4.2 on 2024-08-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_status'),
        ('notification', '0004_notification_status_alter_notification_target_user'),
    ]

    operations = [
    ]
